config/routes.rb
Komatsublog::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "wanted/list"

  get "wanted/new_issue"

  get "wanted/detail"

  resources :good_points

  resources :comments

  resources :issues

  resources :users

end

app/models/good_point.rb
class GoodPoint < ActiveRecord::Base
  attr_accessible :count, :issue_id, :user_id
end

app/controllers/good_points_controller.rb
class GoodPointsController < ApplicationController
  # GET /good_points
  # GET /good_points.json
  def index
    @good_points = GoodPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @good_points }
    end
  end

  # GET /good_points/1
  # GET /good_points/1.json
  def show
    @good_point = GoodPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good_point }
    end
  end

  # GET /good_points/new
  # GET /good_points/new.json
  def new
    @good_point = GoodPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @good_point }
    end
  end

  # GET /good_points/1/edit
  def edit
    @good_point = GoodPoint.find(params[:id])
  end

  # POST /good_points
  # POST /good_points.json
  def create
    @good_point = GoodPoint.new(params[:good_point])

    respond_to do |format|
      if @good_point.save
        format.html { redirect_to @good_point, notice: 'Good point was successfully created.' }
        format.json { render json: @good_point, status: :created, location: @good_point }
      else
        format.html { render action: "new" }
        format.json { render json: @good_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /good_points/1
  # PUT /good_points/1.json
  def update
    @good_point = GoodPoint.find(params[:id])

    respond_to do |format|
      if @good_point.update_attributes(params[:good_point])
        format.html { redirect_to @good_point, notice: 'Good point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @good_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /good_points/1
  # DELETE /good_points/1.json
  def destroy
    @good_point = GoodPoint.find(params[:id])
    @good_point.destroy

    respond_to do |format|
      format.html { redirect_to good_points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/good_points_helper.rb
module GoodPointsHelper
end

app/views/good_points/_form.html.erb
<%= form_for(@good_point) do |f| %>
  <% if @good_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good_point.errors.count, "error") %> prohibited this good_point from being saved:</h2>

      <ul>
      <% @good_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_id %><br />
    <%= f.number_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/good_points/edit.html.erb
<h1>Editing good_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @good_point %> |
<%= link_to 'Back', good_points_path %>

app/views/good_points/index.html.erb
<h1>Listing good_points</h1>

<table>
  <tr>
    <th>Issue</th>
    <th>User</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @good_points.each do |good_point| %>
  <tr>
    <td><%= good_point.issue_id %></td>
    <td><%= good_point.user_id %></td>
    <td><%= good_point.count %></td>
    <td><%= link_to 'Show', good_point %></td>
    <td><%= link_to 'Edit', edit_good_point_path(good_point) %></td>
    <td><%= link_to 'Destroy', good_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Good point', new_good_point_path %>

app/views/good_points/new.html.erb
<h1>New good_point</h1>

<%= render 'form' %>

<%= link_to 'Back', good_points_path %>

app/views/good_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue:</b>
  <%= @good_point.issue_id %>
</p>

<p>
  <b>User:</b>
  <%= @good_point.user_id %>
</p>

<p>
  <b>Count:</b>
  <%= @good_point.count %>
</p>


<%= link_to 'Edit', edit_good_point_path(@good_point) %> |
<%= link_to 'Back', good_points_path %>